server:
  port: 8180
  context-path: /chatboxapp
      
logging:
  level:
    org.springframework.web: DEBUG
    onlinejudge: DEBUG
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
path:
  submitRootPath: C:\Users\oONhuocQuyOo\Desktop\tmp\data\allSubmit
  dataRootPath: C:\Users\oONhuocQuyOo\Desktop\tmp\data\input-output
  resultRootPath: C:\Users\oONhuocQuyOo\Desktop\tmp\data\result
  messageChatBox: C:\Users\oONhuocQuyOo\Desktop\tmp\data\chatbox
chatbox:
  maxMessage: 3
