server:
  port: 8080
      
logging:
  level:
    org.springframework.web: ERROR
    onlinejudge: DEBUG
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
path:
  submitRootPath: D:/hle56/test/allSubmit
  dataRootPath: D:/hle56/test/data
  messageChatBox: D:/hle56/test/chatbox
chatbox:
  maxMessage: 3
